### [CVE-2025-61783](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-61783)
![](https://img.shields.io/static/v1?label=Product&message=social-app-django&color=blue)
![](https://img.shields.io/static/v1?label=Version&message=%3C%205.6.0%20&color=brightgreen)
![](https://img.shields.io/static/v1?label=Vulnerability&message=CWE-303%3A%20Incorrect%20Implementation%20of%20Authentication%20Algorithm&color=brightgreen)

### Description

Python Social Auth is a social authentication/registration mechanism. In versions prior to 5.6.0, upon authentication, the user could be associated by e-mail even if the `associate_by_email` pipeline was not included. This could lead to account compromise when a third-party authentication service does not validate provided e-mail addresses or doesn't require unique e-mail addresses. Version 5.6.0 contains a patch. As a workaround, review the authentication service policy on e-mail addresses; many will not allow exploiting this vulnerability.

### POC

#### Reference
No PoCs from references.

#### Github
- https://github.com/fkie-cad/nvd-json-data-feeds

